disabled = false
languageCode = "zh-cn"
languageName = "简体中文"
weight = 2
title = "Code // Horizon"

[params]
displayName = "简体中文"
isoCode = "zh-cn"
rtl = false
dateFormat = "2006-01-02"
# logo = "img/logo.png"
# secondaryLogo = "img/secondary-logo.png"
# description = "My awesome website"
copyright = "@ 2025 Code // Horizon"

[params.author]
name = "Kieran"
image = "img/author.png"
headline = "越过山丘，才发现无人等候"
bio = "软件工程师、Vimer、喜欢折腾"
links = [
  { email = "oldmeatovo@gmail.com" },
  { github = "https://github.com/uncoder404" },
]
