#config/_default/languages.zh-Hans.toml

languageName = "简体中文"
languageCode = "zh-Hans"
languageDirection = "ltr"
weight = 1

title = "Kieran's Blog"
copyright = "© 2025 Kieran"

[params]
  dateFormat = "2006-01-02"

  # mainSections = ["section1", "section2"]
  # description = "My awesome website"

[params.author]
    name = "Kieran"
    image = "img/author.png"
    headline = "越过山丘，才发现无人等候"
    bio = "软件工程师、Vimer、喜欢折腾"
    links = [
      {email = "oldmeatovo@gmail.com"},
      {github = "https://github.com/uncoder404"}
    ]
