disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Code // Horizon"

[params]
displayName = "English"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
# logo = "img/logo.png"
# secondaryLogo = "img/secondary-logo.png"
# description = "My awesome website"
# copyright = "Copy, _right?_ :thinking_face:"

[params.author]
name = "Kieran"
image = "img/author.png"
headline = "Over the mountains, mountains."
bio = "A software engineer, Vimer."
links = [
  { email = "oldmeatovo@gmail.com" },
  { github = "https://github.com/uncoder404" },
]
