defaultAppearance = "light"
enableSearch = true
enableCodeCopy = false

[header]
    layout = "basic" # valid options: basic, hamburger, hybrid, custom
    # logo = "img/logo.jpg"
    # logoDark = "img/dark-logo.jpg"
    showTitle = true

[homepage]
    layout = "profile"
    showRecent = true
    recentLimit = 5

[article]
    showDate = true
    showDateUpdated = false
    showAuthor = true
    showBreadcrumbs = true
    showDraftLabel = true
    showEdit = true
    showTableOfContents = false

[footer]
    showCopyright = true
    showThemeAttribution = true
    showAppearanceSwitcher = false
    showScrollToTop = true
