defaultAppearance = "light"
enableSearch = true
enableCodeCopy = true
enableImageLazyLoading = true
enableImageWebp = true

[header]
    layout = "basic" # valid options: basic, hamburger, hybrid, custom
    # logo = "img/logo.jpg"
    # logoDark = "img/dark-logo.jpg"
    showTitle = true

[homepage]
    layout = "profile"
    showRecent = true
    recentLimit = 5

[article]
    showDate = true
    showDateUpdated = true
    showAuthor = true
    showBreadcrumbs = true
    showDraftLabel = true
    showEdit = true
    # editURL = "https://github.com/jpanther/congo/tree/dev/exampleSite/content/"
    editAppendPath = true
    showHeadingAnchors = true
    showPagination = true
    invertPagination = false
    showReadingTime = true
    showTableOfContents = true
    showTaxonomies = false
    showWordCount = false
    showComments = false

[footer]
    showCopyright = true
    showThemeAttribution = true
    showAppearanceSwitcher = true
    showScrollToTop = true

[list]
    showBreadcrumbs = true
    showSummary = true
    showTableOfContents = true
    showTaxonomies = false
    groupByYear = false
    paginationWidth = 1